import { expect, test } from '@playwright/test'

import {
  countSales,
  login,
  resetDatabase,
  tapProduct,
  totalSoldCents,
  waitForServiceWorker,
} from './helpers'

/**
 * The central spec. Everything else in this project exists to make it pass.
 *
 * The stand is regularly out of mobile coverage, so this is not an edge case —
 * it is the normal working day. If this breaks, the product does not work.
 */

test.beforeEach(() => {
  resetDatabase()
})

test('sells with no connection and syncs when it returns', async ({ page, context }) => {
  await login(page)
  await waitForServiceWorker(page)

  await context.setOffline(true)

  for (const product of ['Mani japones', 'Semillas', 'Churros']) {
    await tapProduct(page, product)
    await page.getByRole('button', { name: 'Cobrar' }).click()
    await expect(page.getByText('Ventas de hoy')).toBeVisible()
    await page.getByRole('button', { name: 'Vender' }).click()
  }

  // The sales exist for the user immediately, with no server involved.
  await page.getByRole('button', { name: 'Hoy' }).click()
  await expect(page.getByText('3 ventas')).toBeVisible()

  // 0.50 + 0.25 + 1.00
  await expect(page.getByRole('status').first()).toHaveText('$1.75')

  // Each one is marked as not yet sent.
  await expect(page.getByTitle('Todavía no se sincronizó')).toHaveCount(3)

  // Nothing has reached the server, which is the point.
  expect(countSales()).toBe(0)

  await context.setOffline(false)

  // The engine reacts to the online event; the sales arrive without any
  // further interaction.
  await expect.poll(() => countSales(), { timeout: 30_000 }).toBe(3)
  expect(totalSoldCents()).toBe(175)

  // And the pending markers clear on their own.
  await expect(page.getByTitle('Todavía no se sincronizó')).toHaveCount(0, { timeout: 15_000 })
})

test('survives the app being closed while sales are unsent', async ({ page, context }) => {
  await login(page)
  await waitForServiceWorker(page)

  await context.setOffline(true)
  await tapProduct(page, 'Mani japones')
  await tapProduct(page, 'Semillas')
  await page.getByRole('button', { name: 'Cobrar' }).click()
  await expect(page.getByText('Ventas de hoy')).toBeVisible()

  // Closing the page is as close as Playwright gets to iOS reclaiming a
  // backgrounded web app, which happens routinely on the owner's phone. The
  // sale is in IndexedDB, so it has to survive.
  await page.close()

  const reopened = await context.newPage()
  await reopened.goto('/')

  // Still offline: opening the app at all now depends on the service worker
  // serving the cached shell.
  await expect(reopened.getByRole('button', { name: 'Cobrar' })).toBeVisible()
  await reopened.getByRole('button', { name: 'Hoy' }).click()
  await expect(reopened.getByText('1 venta')).toBeVisible()
  await expect(reopened.getByTitle('Todavía no se sincronizó')).toHaveCount(1)

  expect(countSales()).toBe(0)

  await context.setOffline(false)
  await expect.poll(() => countSales(), { timeout: 30_000 }).toBe(1)
  expect(totalSoldCents()).toBe(75)
})

test('does not duplicate a sale when the app is reopened mid-sync', async ({ page, context }) => {
  await login(page)
  await waitForServiceWorker(page)

  await context.setOffline(true)
  await tapProduct(page, 'Churros')
  await page.getByRole('button', { name: 'Cobrar' }).click()
  await expect(page.getByText('Ventas de hoy')).toBeVisible()

  await context.setOffline(false)

  // Reload immediately, so a cycle may well be in flight. The operation id is
  // generated by the client, so the server dedupes whatever arrives twice.
  await page.reload()

  await expect.poll(() => countSales(), { timeout: 30_000 }).toBe(1)

  // Give any second attempt time to land before asserting it did not.
  await page.waitForTimeout(3_000)
  expect(countSales()).toBe(1)
  expect(totalSoldCents()).toBe(100)
})

test('keeps selling when the session is revoked, and uploads after logging back in', async ({
  page,
  context,
}) => {
  const { sql } = await import('./helpers')

  await login(page)
  await waitForServiceWorker(page)

  // Revoke from the server side, as if the session had been closed from the
  // other phone.
  sql('UPDATE sessions SET revoked_at = now()')

  await tapProduct(page, 'Mani japones')
  await page.getByRole('button', { name: 'Cobrar' }).click()

  // Selling must keep working. The outbox holds business data, not HTTP
  // requests, so an auth failure pauses syncing and touches nothing else.
  await expect(page.getByText('Ventas de hoy')).toBeVisible()
  await expect(page.getByText('1 venta')).toBeVisible()
  expect(countSales()).toBe(0)

  await expect(page.getByText(/sesión venció/i)).toBeVisible({ timeout: 20_000 })

  // The queued sale is still there, unsent and undamaged.
  await expect(page.getByTitle('Todavía no se sincronizó')).toHaveCount(1)

  void context
})
